### ISSUE TITLE
Share code for samples?

### ISSUE THREAD

**Issue by dannybess** [axmz/react-searchbox-awesome#1]
Hey! 

Great search bar -- was wondering if you could share the code for the two other samples pictured in the repo?

**Comment by axmz** [comment]
Sorry for late response.
Added them to the sandbox [here](https://codesandbox.io/embed/serene-star-ffwq2?fontsize=14&hidenavigation=1&theme=dark&view=preview). 
Check them out in the App.js (style and activeStyle properties)
